/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as CertificationDataDetailsRouteImport } from './routes/certification-data-details'
import { Route as CustomerDetailsRouteImport } from './routes/customer-details'
import { Route as FacilityHeadOfficeEditRouteImport } from './routes/facility-head-office-edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationDataDetailsRoute =
  CertificationDataDetailsRouteImport.update({
    id: '/certification-data-details',
    path: '/certification-data-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDetailsRoute = CustomerDetailsRouteImport.update({
  id: '/customer-details',
  path: '/customer-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityHeadOfficeEditRoute = FacilityHeadOfficeEditRouteImport.update({
  id: '/facility-head-office-edit',
  path: '/facility-head-office-edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/certification-data-details': typeof CertificationDataDetailsRoute
  '/customer-details': typeof CustomerDetailsRoute
  '/facility-head-office-edit': typeof FacilityHeadOfficeEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/certification-data-details': typeof CertificationDataDetailsRoute
  '/customer-details': typeof CustomerDetailsRoute
  '/facility-head-office-edit': typeof FacilityHeadOfficeEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/certification-data-details': typeof CertificationDataDetailsRoute
  '/customer-details': typeof CustomerDetailsRoute
  '/facility-head-office-edit': typeof FacilityHeadOfficeEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/certification-data-details'
    | '/customer-details'
    | '/facility-head-office-edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/certification-data-details'
    | '/customer-details'
    | '/facility-head-office-edit'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/certification-data-details'
    | '/customer-details'
    | '/facility-head-office-edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  CertificationDataDetailsRoute: typeof CertificationDataDetailsRoute
  CustomerDetailsRoute: typeof CustomerDetailsRoute
  FacilityHeadOfficeEditRoute: typeof FacilityHeadOfficeEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-data-details': {
      id: '/certification-data-details'
      path: '/certification-data-details'
      fullPath: '/certification-data-details'
      preLoaderRoute: typeof CertificationDataDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-details': {
      id: '/customer-details'
      path: '/customer-details'
      fullPath: '/customer-details'
      preLoaderRoute: typeof CustomerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility-head-office-edit': {
      id: '/facility-head-office-edit'
      path: '/facility-head-office-edit'
      fullPath: '/facility-head-office-edit'
      preLoaderRoute: typeof FacilityHeadOfficeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  CertificationDataDetailsRoute: CertificationDataDetailsRoute,
  CustomerDetailsRoute: CustomerDetailsRoute,
  FacilityHeadOfficeEditRoute: FacilityHeadOfficeEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
